import { useState } from 'react'
import {
  Puzzle, Play, CheckCircle2, AlertCircle, XCircle, Settings,
  ChevronDown, ChevronRight, ExternalLink, RefreshCw, Code,
  ArrowUpRight, ArrowDownRight, Activity, Clock, Zap, Globe,
  Save, Wifi, WifiOff
} from 'lucide-react'
import { Button } from '@/components/ui/button.jsx'
import { cn } from '../../lib/utils.js'
import { PLUGINS } from '../../lib/workflow-data.js'

/* ─── Plugin Status Badge — Cursor warm ─── */
function PluginStatusBadge({ status, ...qoderProps }) {
  const config = {
    active: { label: '运行中', bg: 'hsl(159 40% 94%)', color: 'var(--cursor-success)', dot: 'var(--cursor-success)' },
    standby: { label: '待命', bg: 'var(--cursor-surface-500)', color: 'var(--cursor-border-55)', dot: 'var(--cursor-border-55)' },
    error: { label: '异常', bg: 'hsl(345 60% 96%)', color: 'var(--cursor-error)', dot: 'var(--cursor-error)' },
  }
  const c = config[status] || config.standby
  return (
    <span className={["inline-flex items-center gap-1 rounded-full px-2 py-0.5 text-[10px] font-medium", qoderProps?.className].filter(Boolean).join(" ")} style={{ ...({ background: c.bg, color: c.color, borderRadius: '9999px' }), ...(qoderProps?.style) }} data-qoder-id={qoderProps?.["data-qoder-id"]} data-qoder-source={qoderProps?.["data-qoder-source"]}>
      <span className={cn('h-1.5 w-1.5 rounded-full', status === 'active' && 'animate-pulse')} style={{ background: c.dot }}  data-qoder-id="qel-span-36e0e39b" data-qoder-source="{&quot;qoderId&quot;:&quot;qel-span-36e0e39b&quot;,&quot;filePath&quot;:&quot;react-vite/src/components/workflow/PluginManager.jsx&quot;,&quot;componentName&quot;:&quot;PluginStatusBadge&quot;,&quot;elementRole&quot;:&quot;span&quot;,&quot;loc&quot;:{&quot;line&quot;:22,&quot;column&quot;:7}}"/>
      {c.label}
    </span>
  )
}

/* ─── Field Schema Table — Cursor ─── */
function FieldSchema({ title, fields, direction, ...qoderProps }) {
  const DirIcon = direction === 'in' ? ArrowDownRight : ArrowUpRight
  return (
    <div data-component={`field-schema-${direction}`} style={qoderProps?.style} className={qoderProps?.className} data-qoder-id={qoderProps?.["data-qoder-id"]} data-qoder-source={qoderProps?.["data-qoder-source"]}>
      <div className="flex items-center gap-1.5 mb-2" data-qoder-id="qel-flex-2792210c" data-qoder-source="{&quot;qoderId&quot;:&quot;qel-flex-2792210c&quot;,&quot;filePath&quot;:&quot;react-vite/src/components/workflow/PluginManager.jsx&quot;,&quot;componentName&quot;:&quot;FieldSchema&quot;,&quot;elementRole&quot;:&quot;flex&quot;,&quot;loc&quot;:{&quot;line&quot;:33,&quot;column&quot;:7}}">
        <DirIcon className="h-3 w-3" style={{ color: 'var(--cursor-border-55)' }}  data-qoder-id="qel-h-3-6a305e2f" data-qoder-source="{&quot;qoderId&quot;:&quot;qel-h-3-6a305e2f&quot;,&quot;filePath&quot;:&quot;react-vite/src/components/workflow/PluginManager.jsx&quot;,&quot;componentName&quot;:&quot;FieldSchema&quot;,&quot;elementRole&quot;:&quot;h-3&quot;,&quot;loc&quot;:{&quot;line&quot;:34,&quot;column&quot;:9}}"/>
        <h5 className="text-[11px] font-medium uppercase tracking-wider" style={{ color: 'var(--cursor-border-55)' }} data-qoder-id="qel-text-11px-b94d827b" data-qoder-source="{&quot;qoderId&quot;:&quot;qel-text-11px-b94d827b&quot;,&quot;filePath&quot;:&quot;react-vite/src/components/workflow/PluginManager.jsx&quot;,&quot;componentName&quot;:&quot;FieldSchema&quot;,&quot;elementRole&quot;:&quot;text-11px&quot;,&quot;loc&quot;:{&quot;line&quot;:35,&quot;column&quot;:9}}">{title}</h5>
        <span className="ml-auto text-[10px]" style={{ color: 'var(--cursor-border-55)' }} data-qoder-id="qel-ml-auto-a4a8acac" data-qoder-source="{&quot;qoderId&quot;:&quot;qel-ml-auto-a4a8acac&quot;,&quot;filePath&quot;:&quot;react-vite/src/components/workflow/PluginManager.jsx&quot;,&quot;componentName&quot;:&quot;FieldSchema&quot;,&quot;elementRole&quot;:&quot;ml-auto&quot;,&quot;loc&quot;:{&quot;line&quot;:36,&quot;column&quot;:9}}">{fields.length} 字段</span>
      </div>
      <div className="space-y-1" data-qoder-id="qel-space-y-1-cfe50a07" data-qoder-source="{&quot;qoderId&quot;:&quot;qel-space-y-1-cfe50a07&quot;,&quot;filePath&quot;:&quot;react-vite/src/components/workflow/PluginManager.jsx&quot;,&quot;componentName&quot;:&quot;FieldSchema&quot;,&quot;elementRole&quot;:&quot;space-y-1&quot;,&quot;loc&quot;:{&quot;line&quot;:38,&quot;column&quot;:7}}">
        {fields.map((field) => (
          <div key={field} className="flex items-center gap-2 rounded-md px-2.5 py-1.5 border" style={{ background: 'var(--cursor-surface-100)', borderColor: 'var(--cursor-border-10)' }} data-qoder-id="qel-flex-2c9228eb" data-qoder-source="{&quot;qoderId&quot;:&quot;qel-flex-2c9228eb&quot;,&quot;filePath&quot;:&quot;react-vite/src/components/workflow/PluginManager.jsx&quot;,&quot;componentName&quot;:&quot;FieldSchema&quot;,&quot;elementRole&quot;:&quot;flex&quot;,&quot;loc&quot;:{&quot;line&quot;:40,&quot;column&quot;:11}}">
            <Code className="h-3 w-3" style={{ color: 'var(--cursor-orange)' }}  data-qoder-id="qel-h-3-95f377c4" data-qoder-source="{&quot;qoderId&quot;:&quot;qel-h-3-95f377c4&quot;,&quot;filePath&quot;:&quot;react-vite/src/components/workflow/PluginManager.jsx&quot;,&quot;componentName&quot;:&quot;FieldSchema&quot;,&quot;elementRole&quot;:&quot;h-3&quot;,&quot;loc&quot;:{&quot;line&quot;:41,&quot;column&quot;:13}}"/>
            <span className="text-xs font-mono" style={{ color: 'var(--cursor-ink)' }} data-qoder-id="qel-text-xs-8b57d09d" data-qoder-source="{&quot;qoderId&quot;:&quot;qel-text-xs-8b57d09d&quot;,&quot;filePath&quot;:&quot;react-vite/src/components/workflow/PluginManager.jsx&quot;,&quot;componentName&quot;:&quot;FieldSchema&quot;,&quot;elementRole&quot;:&quot;text-xs&quot;,&quot;loc&quot;:{&quot;line&quot;:42,&quot;column&quot;:13}}">{field}</span>
          </div>
        ))}
      </div>
    </div>
  )
}

/* ─── Plugin Test Panel — Cursor ─── */
function PluginTestPanel({ plugin, ...qoderProps }) {
  const [testInput, setTestInput] = useState('')
  const [testOutput, setTestOutput] = useState(null)
  const [isRunning, setIsRunning] = useState(false)

  const handleRunTest = () => {
    setIsRunning(true)
    setTimeout(() => {
      const mockOutputs = {
        query_compensation: { compensation_allowed: true, solution_type: 'refund_and_coupon', refund_amount: 19, coupon_amount: 30, store_callback_required: true, human_followup_required: false },
        query_history: { history_found: true, repeat_customer: false, complaint_count: 1, food_safety_count: 0, high_risk_history: false },
        store_query: { store_found: true, store_id: 'SZ-NT-042', store_name: '南山科技园店', city: '深圳', district: '南山区', handler_group: '深圳南区客服组', callback_sla_hours: 4 },
        query_order: { success: false, order_verified: false, query_key_type: 'order_id', query_key: 'H1254118723283854849844', next_action_hint: 'ask_order_or_label_image', error_code: 'ORDER_API_NOT_CONFIGURED', order_summary: '订单号：H1254118723283854849844' },
      }
      setTestOutput(mockOutputs[plugin.id] || { result: 'ok' })
      setIsRunning(false)
    }, 800)
  }

  return (
    <div className={["border-t p-4 space-y-3", qoderProps?.className].filter(Boolean).join(" ")} style={{ ...({ borderColor: 'var(--cursor-border-10)' }), ...(qoderProps?.style) }} data-component="plugin-test-panel" data-qoder-id={qoderProps?.["data-qoder-id"]} data-qoder-source={qoderProps?.["data-qoder-source"]}>
      <div className="flex items-center justify-between" data-qoder-id="qel-flex-9982d24c" data-qoder-source="{&quot;qoderId&quot;:&quot;qel-flex-9982d24c&quot;,&quot;filePath&quot;:&quot;react-vite/src/components/workflow/PluginManager.jsx&quot;,&quot;componentName&quot;:&quot;PluginTestPanel&quot;,&quot;elementRole&quot;:&quot;flex&quot;,&quot;loc&quot;:{&quot;line&quot;:71,&quot;column&quot;:7}}">
        <h5 className="text-xs font-semibold cursor-title" style={{ color: 'var(--cursor-ink)' }} data-qoder-id="qel-text-xs-b35619ab" data-qoder-source="{&quot;qoderId&quot;:&quot;qel-text-xs-b35619ab&quot;,&quot;filePath&quot;:&quot;react-vite/src/components/workflow/PluginManager.jsx&quot;,&quot;componentName&quot;:&quot;PluginTestPanel&quot;,&quot;elementRole&quot;:&quot;text-xs&quot;,&quot;loc&quot;:{&quot;line&quot;:72,&quot;column&quot;:9}}">接口测试</h5>
        <Button variant="ghost" size="sm" onClick={handleRunTest} disabled={isRunning} className="h-7" style={{ borderRadius: 'var(--seed-radius)' }} data-qoder-id="qel-h-7-bdf6d1d8" data-qoder-source="{&quot;qoderId&quot;:&quot;qel-h-7-bdf6d1d8&quot;,&quot;filePath&quot;:&quot;react-vite/src/components/workflow/PluginManager.jsx&quot;,&quot;componentName&quot;:&quot;PluginTestPanel&quot;,&quot;elementRole&quot;:&quot;h-7&quot;,&quot;loc&quot;:{&quot;line&quot;:73,&quot;column&quot;:9}}">
          {isRunning ? <RefreshCw className="h-3 w-3 mr-1 animate-spin"  data-qoder-id="qel-h-3-5af7cf3e" data-qoder-source="{&quot;qoderId&quot;:&quot;qel-h-3-5af7cf3e&quot;,&quot;filePath&quot;:&quot;react-vite/src/components/workflow/PluginManager.jsx&quot;,&quot;componentName&quot;:&quot;PluginTestPanel&quot;,&quot;elementRole&quot;:&quot;h-3&quot;,&quot;loc&quot;:{&quot;line&quot;:74,&quot;column&quot;:24}}"/> : <Play className="h-3 w-3 mr-1"  data-qoder-id="qel-h-3-63c93b00" data-qoder-source="{&quot;qoderId&quot;:&quot;qel-h-3-63c93b00&quot;,&quot;filePath&quot;:&quot;react-vite/src/components/workflow/PluginManager.jsx&quot;,&quot;componentName&quot;:&quot;PluginTestPanel&quot;,&quot;elementRole&quot;:&quot;h-3&quot;,&quot;loc&quot;:{&quot;line&quot;:74,&quot;column&quot;:78}}"/>}
          {isRunning ? '执行中...' : '模拟调用'}
        </Button>
      </div>
      <div data-qoder-id="qel-div-d279d4f3" data-qoder-source="{&quot;qoderId&quot;:&quot;qel-div-d279d4f3&quot;,&quot;filePath&quot;:&quot;react-vite/src/components/workflow/PluginManager.jsx&quot;,&quot;componentName&quot;:&quot;PluginTestPanel&quot;,&quot;elementRole&quot;:&quot;div&quot;,&quot;loc&quot;:{&quot;line&quot;:78,&quot;column&quot;:7}}">
        <label className="text-[10px] font-medium uppercase tracking-wider" style={{ color: 'var(--cursor-border-55)' }} data-qoder-id="qel-text-10px-58a0f9a3" data-qoder-source="{&quot;qoderId&quot;:&quot;qel-text-10px-58a0f9a3&quot;,&quot;filePath&quot;:&quot;react-vite/src/components/workflow/PluginManager.jsx&quot;,&quot;componentName&quot;:&quot;PluginTestPanel&quot;,&quot;elementRole&quot;:&quot;text-10px&quot;,&quot;loc&quot;:{&quot;line&quot;:79,&quot;column&quot;:9}}">输入参数（模拟）</label>
        <div className="mt-1 flex flex-wrap gap-1" data-qoder-id="qel-mt-1-88d5cab6" data-qoder-source="{&quot;qoderId&quot;:&quot;qel-mt-1-88d5cab6&quot;,&quot;filePath&quot;:&quot;react-vite/src/components/workflow/PluginManager.jsx&quot;,&quot;componentName&quot;:&quot;PluginTestPanel&quot;,&quot;elementRole&quot;:&quot;mt-1&quot;,&quot;loc&quot;:{&quot;line&quot;:80,&quot;column&quot;:9}}">
          {plugin.inputFields.slice(0, 5).map((f) => (
            <span key={f} className="rounded-md px-2 py-0.5 text-[10px] font-mono" style={{ background: 'var(--cursor-surface-300)', color: 'var(--cursor-border-55)' }} data-qoder-id="qel-rounded-md-6d8b91c8" data-qoder-source="{&quot;qoderId&quot;:&quot;qel-rounded-md-6d8b91c8&quot;,&quot;filePath&quot;:&quot;react-vite/src/components/workflow/PluginManager.jsx&quot;,&quot;componentName&quot;:&quot;PluginTestPanel&quot;,&quot;elementRole&quot;:&quot;rounded-md&quot;,&quot;loc&quot;:{&quot;line&quot;:82,&quot;column&quot;:13}}">{f}</span>
          ))}
          {plugin.inputFields.length > 5 && (
            <span className="rounded-md px-2 py-0.5 text-[10px]" style={{ background: 'var(--cursor-surface-300)', color: 'var(--cursor-border-55)' }} data-qoder-id="qel-rounded-md-708b9681" data-qoder-source="{&quot;qoderId&quot;:&quot;qel-rounded-md-708b9681&quot;,&quot;filePath&quot;:&quot;react-vite/src/components/workflow/PluginManager.jsx&quot;,&quot;componentName&quot;:&quot;PluginTestPanel&quot;,&quot;elementRole&quot;:&quot;rounded-md&quot;,&quot;loc&quot;:{&quot;line&quot;:85,&quot;column&quot;:13}}">+{plugin.inputFields.length - 5}</span>
          )}
        </div>
      </div>
      {testOutput && (
        <div className="rounded-lg border overflow-hidden" style={{ borderColor: 'var(--cursor-border-10)' }} data-qoder-id="qel-rounded-lg-6d627eb5" data-qoder-source="{&quot;qoderId&quot;:&quot;qel-rounded-lg-6d627eb5&quot;,&quot;filePath&quot;:&quot;react-vite/src/components/workflow/PluginManager.jsx&quot;,&quot;componentName&quot;:&quot;PluginTestPanel&quot;,&quot;elementRole&quot;:&quot;rounded-lg&quot;,&quot;loc&quot;:{&quot;line&quot;:90,&quot;column&quot;:9}}">
          <div className="flex items-center gap-1.5 px-3 py-1.5" style={{ background: 'hsl(159 40% 94%)' }} data-qoder-id="qel-flex-2685eeda" data-qoder-source="{&quot;qoderId&quot;:&quot;qel-flex-2685eeda&quot;,&quot;filePath&quot;:&quot;react-vite/src/components/workflow/PluginManager.jsx&quot;,&quot;componentName&quot;:&quot;PluginTestPanel&quot;,&quot;elementRole&quot;:&quot;flex&quot;,&quot;loc&quot;:{&quot;line&quot;:91,&quot;column&quot;:11}}">
            <CheckCircle2 className="h-3 w-3" style={{ color: 'var(--cursor-success)' }}  data-qoder-id="qel-h-3-b8723ca1" data-qoder-source="{&quot;qoderId&quot;:&quot;qel-h-3-b8723ca1&quot;,&quot;filePath&quot;:&quot;react-vite/src/components/workflow/PluginManager.jsx&quot;,&quot;componentName&quot;:&quot;PluginTestPanel&quot;,&quot;elementRole&quot;:&quot;h-3&quot;,&quot;loc&quot;:{&quot;line&quot;:92,&quot;column&quot;:13}}"/>
            <span className="text-[10px] font-medium" style={{ color: 'var(--cursor-success)' }} data-qoder-id="qel-text-10px-8ffb3d73" data-qoder-source="{&quot;qoderId&quot;:&quot;qel-text-10px-8ffb3d73&quot;,&quot;filePath&quot;:&quot;react-vite/src/components/workflow/PluginManager.jsx&quot;,&quot;componentName&quot;:&quot;PluginTestPanel&quot;,&quot;elementRole&quot;:&quot;text-10px&quot;,&quot;loc&quot;:{&quot;line&quot;:93,&quot;column&quot;:13}}">200 OK · 模拟响应</span>
          </div>
          <pre className="p-3 text-xs font-mono leading-relaxed overflow-x-auto scrollbar-thin" style={{ background: 'var(--cursor-surface-100)', color: 'var(--cursor-ink)' }} data-qoder-id="qel-p-3-1fb31416" data-qoder-source="{&quot;qoderId&quot;:&quot;qel-p-3-1fb31416&quot;,&quot;filePath&quot;:&quot;react-vite/src/components/workflow/PluginManager.jsx&quot;,&quot;componentName&quot;:&quot;PluginTestPanel&quot;,&quot;elementRole&quot;:&quot;p-3&quot;,&quot;loc&quot;:{&quot;line&quot;:95,&quot;column&quot;:11}}">{JSON.stringify(testOutput, null, 2)}</pre>
        </div>
      )}
    </div>
  )
}

/* ─── Endpoint Config Panel — Cursor ─── */
function EndpointConfigPanel({ plugin, ...qoderProps }) {
  const [endpoint, setEndpoint] = useState(plugin.endpoint || { url: '', method: 'POST', auth: 'bearer_token', timeout: 5000 })
  const [testResult, setTestResult] = useState(null)
  const [isTesting, setIsTesting] = useState(false)

  const handleTestConnection = () => {
    setIsTesting(true)
    setTimeout(() => {
      setTestResult({ success: true, latency: Math.floor(30 + Math.random() * 70), statusCode: 200, message: '连接成功，API 响应正常' })
      setIsTesting(false)
    }, 1000)
  }

  const inputStyle = { background: 'var(--cursor-surface-100)', borderColor: 'var(--cursor-border-10)', color: 'var(--cursor-ink)' }

  return (
    <div className={["border-t p-4 space-y-3", qoderProps?.className].filter(Boolean).join(" ")} style={{ ...({ borderColor: 'var(--cursor-border-10)' }), ...(qoderProps?.style) }} data-component="endpoint-config" data-qoder-id={qoderProps?.["data-qoder-id"]} data-qoder-source={qoderProps?.["data-qoder-source"]}>
      <div className="flex items-center justify-between" data-qoder-id="qel-flex-1d38b3d5" data-qoder-source="{&quot;qoderId&quot;:&quot;qel-flex-1d38b3d5&quot;,&quot;filePath&quot;:&quot;react-vite/src/components/workflow/PluginManager.jsx&quot;,&quot;componentName&quot;:&quot;EndpointConfigPanel&quot;,&quot;elementRole&quot;:&quot;flex&quot;,&quot;loc&quot;:{&quot;line&quot;:120,&quot;column&quot;:7}}">
        <h5 className="text-xs font-semibold cursor-title" style={{ color: 'var(--cursor-ink)' }} data-qoder-id="qel-text-xs-864032d1" data-qoder-source="{&quot;qoderId&quot;:&quot;qel-text-xs-864032d1&quot;,&quot;filePath&quot;:&quot;react-vite/src/components/workflow/PluginManager.jsx&quot;,&quot;componentName&quot;:&quot;EndpointConfigPanel&quot;,&quot;elementRole&quot;:&quot;text-xs&quot;,&quot;loc&quot;:{&quot;line&quot;:121,&quot;column&quot;:9}}">API 端点配置</h5>
        <Button variant="ghost" size="sm" className="h-7" onClick={handleTestConnection} disabled={isTesting} style={{ borderRadius: 'var(--seed-radius)' }} data-qoder-id="qel-h-7-146e1c7e" data-qoder-source="{&quot;qoderId&quot;:&quot;qel-h-7-146e1c7e&quot;,&quot;filePath&quot;:&quot;react-vite/src/components/workflow/PluginManager.jsx&quot;,&quot;componentName&quot;:&quot;EndpointConfigPanel&quot;,&quot;elementRole&quot;:&quot;h-7&quot;,&quot;loc&quot;:{&quot;line&quot;:122,&quot;column&quot;:9}}">
          {isTesting ? <RefreshCw className="h-3 w-3 mr-1 animate-spin"  data-qoder-id="qel-h-3-42be9644" data-qoder-source="{&quot;qoderId&quot;:&quot;qel-h-3-42be9644&quot;,&quot;filePath&quot;:&quot;react-vite/src/components/workflow/PluginManager.jsx&quot;,&quot;componentName&quot;:&quot;EndpointConfigPanel&quot;,&quot;elementRole&quot;:&quot;h-3&quot;,&quot;loc&quot;:{&quot;line&quot;:123,&quot;column&quot;:24}}"/> : <Wifi className="h-3 w-3 mr-1"  data-qoder-id="qel-h-3-d6bea74b" data-qoder-source="{&quot;qoderId&quot;:&quot;qel-h-3-d6bea74b&quot;,&quot;filePath&quot;:&quot;react-vite/src/components/workflow/PluginManager.jsx&quot;,&quot;componentName&quot;:&quot;EndpointConfigPanel&quot;,&quot;elementRole&quot;:&quot;h-3&quot;,&quot;loc&quot;:{&quot;line&quot;:123,&quot;column&quot;:78}}"/>}
          {isTesting ? '测试中...' : '测试连接'}
        </Button>
      </div>
      <div data-qoder-id="qel-div-cd0af809" data-qoder-source="{&quot;qoderId&quot;:&quot;qel-div-cd0af809&quot;,&quot;filePath&quot;:&quot;react-vite/src/components/workflow/PluginManager.jsx&quot;,&quot;componentName&quot;:&quot;EndpointConfigPanel&quot;,&quot;elementRole&quot;:&quot;div&quot;,&quot;loc&quot;:{&quot;line&quot;:127,&quot;column&quot;:7}}">
        <label className="text-[10px] font-medium uppercase tracking-wider" style={{ color: 'var(--cursor-border-55)' }} data-qoder-id="qel-text-10px-043ab46d" data-qoder-source="{&quot;qoderId&quot;:&quot;qel-text-10px-043ab46d&quot;,&quot;filePath&quot;:&quot;react-vite/src/components/workflow/PluginManager.jsx&quot;,&quot;componentName&quot;:&quot;EndpointConfigPanel&quot;,&quot;elementRole&quot;:&quot;text-10px&quot;,&quot;loc&quot;:{&quot;line&quot;:128,&quot;column&quot;:9}}">端点 URL</label>
        <div className="mt-1 flex items-center gap-1.5" data-qoder-id="qel-mt-1-1da8322d" data-qoder-source="{&quot;qoderId&quot;:&quot;qel-mt-1-1da8322d&quot;,&quot;filePath&quot;:&quot;react-vite/src/components/workflow/PluginManager.jsx&quot;,&quot;componentName&quot;:&quot;EndpointConfigPanel&quot;,&quot;elementRole&quot;:&quot;mt-1&quot;,&quot;loc&quot;:{&quot;line&quot;:129,&quot;column&quot;:9}}">
          <select value={endpoint.method} onChange={(e) => setEndpoint({ ...endpoint, method: e.target.value })} className="rounded-lg border px-2 py-1.5 text-xs font-mono font-bold focus:outline-none" style={{ ...inputStyle, color: 'var(--cursor-orange)' }} data-qoder-id="qel-rounded-lg-1821bb73" data-qoder-source="{&quot;qoderId&quot;:&quot;qel-rounded-lg-1821bb73&quot;,&quot;filePath&quot;:&quot;react-vite/src/components/workflow/PluginManager.jsx&quot;,&quot;componentName&quot;:&quot;EndpointConfigPanel&quot;,&quot;elementRole&quot;:&quot;rounded-lg&quot;,&quot;loc&quot;:{&quot;line&quot;:130,&quot;column&quot;:11}}">
            <option value="GET" data-qoder-id="qel-option-8f32483f" data-qoder-source="{&quot;qoderId&quot;:&quot;qel-option-8f32483f&quot;,&quot;filePath&quot;:&quot;react-vite/src/components/workflow/PluginManager.jsx&quot;,&quot;componentName&quot;:&quot;EndpointConfigPanel&quot;,&quot;elementRole&quot;:&quot;option&quot;,&quot;loc&quot;:{&quot;line&quot;:131,&quot;column&quot;:13}}">GET</option><option value="POST" data-qoder-id="qel-option-8e3246ac" data-qoder-source="{&quot;qoderId&quot;:&quot;qel-option-8e3246ac&quot;,&quot;filePath&quot;:&quot;react-vite/src/components/workflow/PluginManager.jsx&quot;,&quot;componentName&quot;:&quot;EndpointConfigPanel&quot;,&quot;elementRole&quot;:&quot;option&quot;,&quot;loc&quot;:{&quot;line&quot;:131,&quot;column&quot;:45}}">POST</option><option value="PUT" data-qoder-id="qel-option-8d20fbf8" data-qoder-source="{&quot;qoderId&quot;:&quot;qel-option-8d20fbf8&quot;,&quot;filePath&quot;:&quot;react-vite/src/components/workflow/PluginManager.jsx&quot;,&quot;componentName&quot;:&quot;EndpointConfigPanel&quot;,&quot;elementRole&quot;:&quot;option&quot;,&quot;loc&quot;:{&quot;line&quot;:131,&quot;column&quot;:79}}">PUT</option>
          </select>
          <input type="text" value={endpoint.url} onChange={(e) => setEndpoint({ ...endpoint, url: e.target.value })} className="flex-1 rounded-lg border px-3 py-1.5 text-xs font-mono focus:outline-none focus:border-[var(--cursor-orange)]" style={inputStyle} placeholder="https://api.example.com/v3/plugin"  data-qoder-id="qel-flex-1-e8407f92" data-qoder-source="{&quot;qoderId&quot;:&quot;qel-flex-1-e8407f92&quot;,&quot;filePath&quot;:&quot;react-vite/src/components/workflow/PluginManager.jsx&quot;,&quot;componentName&quot;:&quot;EndpointConfigPanel&quot;,&quot;elementRole&quot;:&quot;flex-1&quot;,&quot;loc&quot;:{&quot;line&quot;:133,&quot;column&quot;:11}}"/>
        </div>
      </div>
      <div className="grid grid-cols-2 gap-3" data-qoder-id="qel-grid-d364fec7" data-qoder-source="{&quot;qoderId&quot;:&quot;qel-grid-d364fec7&quot;,&quot;filePath&quot;:&quot;react-vite/src/components/workflow/PluginManager.jsx&quot;,&quot;componentName&quot;:&quot;EndpointConfigPanel&quot;,&quot;elementRole&quot;:&quot;grid&quot;,&quot;loc&quot;:{&quot;line&quot;:136,&quot;column&quot;:7}}">
        <div data-qoder-id="qel-div-5e038d87" data-qoder-source="{&quot;qoderId&quot;:&quot;qel-div-5e038d87&quot;,&quot;filePath&quot;:&quot;react-vite/src/components/workflow/PluginManager.jsx&quot;,&quot;componentName&quot;:&quot;EndpointConfigPanel&quot;,&quot;elementRole&quot;:&quot;div&quot;,&quot;loc&quot;:{&quot;line&quot;:137,&quot;column&quot;:9}}">
          <label className="text-[10px] font-medium uppercase tracking-wider" style={{ color: 'var(--cursor-border-55)' }} data-qoder-id="qel-text-10px-052dea0d" data-qoder-source="{&quot;qoderId&quot;:&quot;qel-text-10px-052dea0d&quot;,&quot;filePath&quot;:&quot;react-vite/src/components/workflow/PluginManager.jsx&quot;,&quot;componentName&quot;:&quot;EndpointConfigPanel&quot;,&quot;elementRole&quot;:&quot;text-10px&quot;,&quot;loc&quot;:{&quot;line&quot;:138,&quot;column&quot;:11}}">认证方式</label>
          <select value={endpoint.auth} onChange={(e) => setEndpoint({ ...endpoint, auth: e.target.value })} className="mt-1 w-full rounded-lg border px-2.5 py-1.5 text-xs focus:outline-none" style={inputStyle} data-qoder-id="qel-mt-1-d5e97ed4" data-qoder-source="{&quot;qoderId&quot;:&quot;qel-mt-1-d5e97ed4&quot;,&quot;filePath&quot;:&quot;react-vite/src/components/workflow/PluginManager.jsx&quot;,&quot;componentName&quot;:&quot;EndpointConfigPanel&quot;,&quot;elementRole&quot;:&quot;mt-1&quot;,&quot;loc&quot;:{&quot;line&quot;:139,&quot;column&quot;:11}}">
            <option value="bearer_token" data-qoder-id="qel-option-9321056a" data-qoder-source="{&quot;qoderId&quot;:&quot;qel-option-9321056a&quot;,&quot;filePath&quot;:&quot;react-vite/src/components/workflow/PluginManager.jsx&quot;,&quot;componentName&quot;:&quot;EndpointConfigPanel&quot;,&quot;elementRole&quot;:&quot;option&quot;,&quot;loc&quot;:{&quot;line&quot;:140,&quot;column&quot;:13}}">Bearer Token</option><option value="api_key" data-qoder-id="qel-option-942106fd" data-qoder-source="{&quot;qoderId&quot;:&quot;qel-option-942106fd&quot;,&quot;filePath&quot;:&quot;react-vite/src/components/workflow/PluginManager.jsx&quot;,&quot;componentName&quot;:&quot;EndpointConfigPanel&quot;,&quot;elementRole&quot;:&quot;option&quot;,&quot;loc&quot;:{&quot;line&quot;:140,&quot;column&quot;:63}}">API Key (Header)</option><option value="basic" data-qoder-id="qel-option-8520ef60" data-qoder-source="{&quot;qoderId&quot;:&quot;qel-option-8520ef60&quot;,&quot;filePath&quot;:&quot;react-vite/src/components/workflow/PluginManager.jsx&quot;,&quot;componentName&quot;:&quot;EndpointConfigPanel&quot;,&quot;elementRole&quot;:&quot;option&quot;,&quot;loc&quot;:{&quot;line&quot;:140,&quot;column&quot;:112}}">Basic Auth</option><option value="none" data-qoder-id="qel-option-8620f0f3" data-qoder-source="{&quot;qoderId&quot;:&quot;qel-option-8620f0f3&quot;,&quot;filePath&quot;:&quot;react-vite/src/components/workflow/PluginManager.jsx&quot;,&quot;componentName&quot;:&quot;EndpointConfigPanel&quot;,&quot;elementRole&quot;:&quot;option&quot;,&quot;loc&quot;:{&quot;line&quot;:140,&quot;column&quot;:153}}">无认证</option>
          </select>
        </div>
        <div data-qoder-id="qel-div-4505a4c3" data-qoder-source="{&quot;qoderId&quot;:&quot;qel-div-4505a4c3&quot;,&quot;filePath&quot;:&quot;react-vite/src/components/workflow/PluginManager.jsx&quot;,&quot;componentName&quot;:&quot;EndpointConfigPanel&quot;,&quot;elementRole&quot;:&quot;div&quot;,&quot;loc&quot;:{&quot;line&quot;:143,&quot;column&quot;:9}}">
          <label className="text-[10px] font-medium uppercase tracking-wider" style={{ color: 'var(--cursor-border-55)' }} data-qoder-id="qel-text-10px-fc2b9d4b" data-qoder-source="{&quot;qoderId&quot;:&quot;qel-text-10px-fc2b9d4b&quot;,&quot;filePath&quot;:&quot;react-vite/src/components/workflow/PluginManager.jsx&quot;,&quot;componentName&quot;:&quot;EndpointConfigPanel&quot;,&quot;elementRole&quot;:&quot;text-10px&quot;,&quot;loc&quot;:{&quot;line&quot;:144,&quot;column&quot;:11}}">超时 (ms)</label>
          <input type="number" value={endpoint.timeout} onChange={(e) => setEndpoint({ ...endpoint, timeout: parseInt(e.target.value) || 5000 })} className="mt-1 w-full rounded-lg border px-2.5 py-1.5 text-xs focus:outline-none" style={inputStyle}  data-qoder-id="qel-mt-1-dd498e48" data-qoder-source="{&quot;qoderId&quot;:&quot;qel-mt-1-dd498e48&quot;,&quot;filePath&quot;:&quot;react-vite/src/components/workflow/PluginManager.jsx&quot;,&quot;componentName&quot;:&quot;EndpointConfigPanel&quot;,&quot;elementRole&quot;:&quot;mt-1&quot;,&quot;loc&quot;:{&quot;line&quot;:145,&quot;column&quot;:11}}"/>
        </div>
      </div>
      {testResult && (
        <div className="flex items-center gap-2 rounded-lg px-3 py-2 text-xs" style={{ background: testResult.success ? 'hsl(159 40% 94%)' : 'hsl(345 60% 96%)', color: testResult.success ? 'var(--cursor-success)' : 'var(--cursor-error)' }} data-qoder-id="qel-flex-9340295c" data-qoder-source="{&quot;qoderId&quot;:&quot;qel-flex-9340295c&quot;,&quot;filePath&quot;:&quot;react-vite/src/components/workflow/PluginManager.jsx&quot;,&quot;componentName&quot;:&quot;EndpointConfigPanel&quot;,&quot;elementRole&quot;:&quot;flex&quot;,&quot;loc&quot;:{&quot;line&quot;:149,&quot;column&quot;:9}}">
          {testResult.success ? <Wifi className="h-3.5 w-3.5"  data-qoder-id="qel-h-3-5-15fb4942" data-qoder-source="{&quot;qoderId&quot;:&quot;qel-h-3-5-15fb4942&quot;,&quot;filePath&quot;:&quot;react-vite/src/components/workflow/PluginManager.jsx&quot;,&quot;componentName&quot;:&quot;EndpointConfigPanel&quot;,&quot;elementRole&quot;:&quot;h-3-5&quot;,&quot;loc&quot;:{&quot;line&quot;:150,&quot;column&quot;:33}}"/> : <WifiOff className="h-3.5 w-3.5"  data-qoder-id="qel-h-3-5-fec53608" data-qoder-source="{&quot;qoderId&quot;:&quot;qel-h-3-5-fec53608&quot;,&quot;filePath&quot;:&quot;react-vite/src/components/workflow/PluginManager.jsx&quot;,&quot;componentName&quot;:&quot;EndpointConfigPanel&quot;,&quot;elementRole&quot;:&quot;h-3-5&quot;,&quot;loc&quot;:{&quot;line&quot;:150,&quot;column&quot;:68}}"/>}
          <span data-qoder-id="qel-span-aa318f21" data-qoder-source="{&quot;qoderId&quot;:&quot;qel-span-aa318f21&quot;,&quot;filePath&quot;:&quot;react-vite/src/components/workflow/PluginManager.jsx&quot;,&quot;componentName&quot;:&quot;EndpointConfigPanel&quot;,&quot;elementRole&quot;:&quot;span&quot;,&quot;loc&quot;:{&quot;line&quot;:151,&quot;column&quot;:11}}">{testResult.message}</span>
          <span className="ml-auto font-mono" data-qoder-id="qel-ml-auto-147f81d7" data-qoder-source="{&quot;qoderId&quot;:&quot;qel-ml-auto-147f81d7&quot;,&quot;filePath&quot;:&quot;react-vite/src/components/workflow/PluginManager.jsx&quot;,&quot;componentName&quot;:&quot;EndpointConfigPanel&quot;,&quot;elementRole&quot;:&quot;ml-auto&quot;,&quot;loc&quot;:{&quot;line&quot;:152,&quot;column&quot;:11}}">{testResult.latency}ms · {testResult.statusCode}</span>
        </div>
      )}
      <Button variant="ghost" size="sm" className="w-full h-7 text-xs" style={{ borderRadius: 'var(--seed-radius)' }} data-qoder-id="qel-w-full-9bf3f30c" data-qoder-source="{&quot;qoderId&quot;:&quot;qel-w-full-9bf3f30c&quot;,&quot;filePath&quot;:&quot;react-vite/src/components/workflow/PluginManager.jsx&quot;,&quot;componentName&quot;:&quot;EndpointConfigPanel&quot;,&quot;elementRole&quot;:&quot;w-full&quot;,&quot;loc&quot;:{&quot;line&quot;:155,&quot;column&quot;:7}}"><Save className="h-3 w-3 mr-1"  data-qoder-id="qel-h-3-f8db1563" data-qoder-source="{&quot;qoderId&quot;:&quot;qel-h-3-f8db1563&quot;,&quot;filePath&quot;:&quot;react-vite/src/components/workflow/PluginManager.jsx&quot;,&quot;componentName&quot;:&quot;EndpointConfigPanel&quot;,&quot;elementRole&quot;:&quot;h-3&quot;,&quot;loc&quot;:{&quot;line&quot;:155,&quot;column&quot;:119}}"/>保存端点配置</Button>
    </div>
  )
}

/* ─── Plugin Detail Card — Cursor warm card ─── */
function PluginDetailCard({ plugin, isSelected, onSelect, ...qoderProps }) {
  const [expanded, setExpanded] = useState(false)

  return (
    <div
      className={[(cn('rounded-lg border transition-all')), qoderProps?.className].filter(Boolean).join(" ")}
      style={{ ...({
        background: 'var(--cursor-surface-400)',
        borderColor: isSelected ? 'var(--cursor-border-20)' : 'var(--cursor-border-10)',
        boxShadow: isSelected ? 'var(--shadow-ambient)' : 'none',
      }), ...(qoderProps?.style) }}
      data-component="plugin-card"
     data-qoder-id={qoderProps?.["data-qoder-id"]} data-qoder-source={qoderProps?.["data-qoder-source"]}>
      <div className="flex items-start gap-3 p-4 cursor-pointer" onClick={() => { onSelect(plugin); setExpanded(!expanded) }} data-qoder-id="qel-flex-3ee42d74" data-qoder-source="{&quot;qoderId&quot;:&quot;qel-flex-3ee42d74&quot;,&quot;filePath&quot;:&quot;react-vite/src/components/workflow/PluginManager.jsx&quot;,&quot;componentName&quot;:&quot;PluginDetailCard&quot;,&quot;elementRole&quot;:&quot;flex&quot;,&quot;loc&quot;:{&quot;line&quot;:174,&quot;column&quot;:7}}">
        <div className="flex h-10 w-10 items-center justify-center rounded-lg" style={{ background: 'var(--cursor-surface-300)', borderRadius: 'var(--seed-radius)' }} data-qoder-id="qel-flex-41e4322d" data-qoder-source="{&quot;qoderId&quot;:&quot;qel-flex-41e4322d&quot;,&quot;filePath&quot;:&quot;react-vite/src/components/workflow/PluginManager.jsx&quot;,&quot;componentName&quot;:&quot;PluginDetailCard&quot;,&quot;elementRole&quot;:&quot;flex&quot;,&quot;loc&quot;:{&quot;line&quot;:175,&quot;column&quot;:9}}">
          <Puzzle className="h-5 w-5" style={{ color: 'var(--cursor-orange)' }}  data-qoder-id="qel-h-5-9dd3ac5a" data-qoder-source="{&quot;qoderId&quot;:&quot;qel-h-5-9dd3ac5a&quot;,&quot;filePath&quot;:&quot;react-vite/src/components/workflow/PluginManager.jsx&quot;,&quot;componentName&quot;:&quot;PluginDetailCard&quot;,&quot;elementRole&quot;:&quot;h-5&quot;,&quot;loc&quot;:{&quot;line&quot;:176,&quot;column&quot;:11}}"/>
        </div>
        <div className="flex-1 min-w-0" data-qoder-id="qel-flex-1-462f7e69" data-qoder-source="{&quot;qoderId&quot;:&quot;qel-flex-1-462f7e69&quot;,&quot;filePath&quot;:&quot;react-vite/src/components/workflow/PluginManager.jsx&quot;,&quot;componentName&quot;:&quot;PluginDetailCard&quot;,&quot;elementRole&quot;:&quot;flex-1&quot;,&quot;loc&quot;:{&quot;line&quot;:178,&quot;column&quot;:9}}">
          <div className="flex items-center gap-2" data-qoder-id="qel-flex-3ae42728" data-qoder-source="{&quot;qoderId&quot;:&quot;qel-flex-3ae42728&quot;,&quot;filePath&quot;:&quot;react-vite/src/components/workflow/PluginManager.jsx&quot;,&quot;componentName&quot;:&quot;PluginDetailCard&quot;,&quot;elementRole&quot;:&quot;flex&quot;,&quot;loc&quot;:{&quot;line&quot;:179,&quot;column&quot;:11}}">
            <h4 className="text-sm font-semibold cursor-title" style={{ color: 'var(--cursor-ink)' }} data-qoder-id="qel-text-sm-666114d1" data-qoder-source="{&quot;qoderId&quot;:&quot;qel-text-sm-666114d1&quot;,&quot;filePath&quot;:&quot;react-vite/src/components/workflow/PluginManager.jsx&quot;,&quot;componentName&quot;:&quot;PluginDetailCard&quot;,&quot;elementRole&quot;:&quot;text-sm&quot;,&quot;loc&quot;:{&quot;line&quot;:180,&quot;column&quot;:13}}">{plugin.name}</h4>
            <PluginStatusBadge status={plugin.status}  data-qoder-id="qel-pluginstatusbadge-5a9263e6" data-qoder-source="{&quot;qoderId&quot;:&quot;qel-pluginstatusbadge-5a9263e6&quot;,&quot;filePath&quot;:&quot;react-vite/src/components/workflow/PluginManager.jsx&quot;,&quot;componentName&quot;:&quot;PluginDetailCard&quot;,&quot;elementRole&quot;:&quot;pluginstatusbadge&quot;,&quot;loc&quot;:{&quot;line&quot;:181,&quot;column&quot;:13}}"/>
          </div>
          <p className="mt-0.5 text-xs line-clamp-2 cursor-serif" style={{ color: 'var(--cursor-border-55)' }} data-qoder-id="qel-mt-0-5-9baf7b63" data-qoder-source="{&quot;qoderId&quot;:&quot;qel-mt-0-5-9baf7b63&quot;,&quot;filePath&quot;:&quot;react-vite/src/components/workflow/PluginManager.jsx&quot;,&quot;componentName&quot;:&quot;PluginDetailCard&quot;,&quot;elementRole&quot;:&quot;mt-0-5&quot;,&quot;loc&quot;:{&quot;line&quot;:183,&quot;column&quot;:11}}">{plugin.description}</p>
          <div className="mt-2 flex items-center gap-3 text-[10px]" style={{ color: 'var(--cursor-border-55)' }} data-qoder-id="qel-mt-2-0cc6f83f" data-qoder-source="{&quot;qoderId&quot;:&quot;qel-mt-2-0cc6f83f&quot;,&quot;filePath&quot;:&quot;react-vite/src/components/workflow/PluginManager.jsx&quot;,&quot;componentName&quot;:&quot;PluginDetailCard&quot;,&quot;elementRole&quot;:&quot;mt-2&quot;,&quot;loc&quot;:{&quot;line&quot;:184,&quot;column&quot;:11}}">
            <span className="flex items-center gap-1" data-qoder-id="qel-flex-2e5831cf" data-qoder-source="{&quot;qoderId&quot;:&quot;qel-flex-2e5831cf&quot;,&quot;filePath&quot;:&quot;react-vite/src/components/workflow/PluginManager.jsx&quot;,&quot;componentName&quot;:&quot;PluginDetailCard&quot;,&quot;elementRole&quot;:&quot;flex&quot;,&quot;loc&quot;:{&quot;line&quot;:185,&quot;column&quot;:13}}"><Code className="h-3 w-3"  data-qoder-id="qel-h-3-40c1c748" data-qoder-source="{&quot;qoderId&quot;:&quot;qel-h-3-40c1c748&quot;,&quot;filePath&quot;:&quot;react-vite/src/components/workflow/PluginManager.jsx&quot;,&quot;componentName&quot;:&quot;PluginDetailCard&quot;,&quot;elementRole&quot;:&quot;h-3&quot;,&quot;loc&quot;:{&quot;line&quot;:185,&quot;column&quot;:55}}"/>v{plugin.version}</span>
            <span className="flex items-center gap-1" data-qoder-id="qel-flex-305834f5" data-qoder-source="{&quot;qoderId&quot;:&quot;qel-flex-305834f5&quot;,&quot;filePath&quot;:&quot;react-vite/src/components/workflow/PluginManager.jsx&quot;,&quot;componentName&quot;:&quot;PluginDetailCard&quot;,&quot;elementRole&quot;:&quot;flex&quot;,&quot;loc&quot;:{&quot;line&quot;:186,&quot;column&quot;:13}}"><Activity className="h-3 w-3"  data-qoder-id="qel-h-3-f8fd76f6" data-qoder-source="{&quot;qoderId&quot;:&quot;qel-h-3-f8fd76f6&quot;,&quot;filePath&quot;:&quot;react-vite/src/components/workflow/PluginManager.jsx&quot;,&quot;componentName&quot;:&quot;PluginDetailCard&quot;,&quot;elementRole&quot;:&quot;h-3&quot;,&quot;loc&quot;:{&quot;line&quot;:186,&quot;column&quot;:55}}"/>{plugin.callCount} 次调用</span>
            <span className="flex items-center gap-1" data-qoder-id="qel-flex-2a582b83" data-qoder-source="{&quot;qoderId&quot;:&quot;qel-flex-2a582b83&quot;,&quot;filePath&quot;:&quot;react-vite/src/components/workflow/PluginManager.jsx&quot;,&quot;componentName&quot;:&quot;PluginDetailCard&quot;,&quot;elementRole&quot;:&quot;flex&quot;,&quot;loc&quot;:{&quot;line&quot;:187,&quot;column&quot;:13}}"><Clock className="h-3 w-3"  data-qoder-id="qel-h-3-b3bf3067" data-qoder-source="{&quot;qoderId&quot;:&quot;qel-h-3-b3bf3067&quot;,&quot;filePath&quot;:&quot;react-vite/src/components/workflow/PluginManager.jsx&quot;,&quot;componentName&quot;:&quot;PluginDetailCard&quot;,&quot;elementRole&quot;:&quot;h-3&quot;,&quot;loc&quot;:{&quot;line&quot;:187,&quot;column&quot;:55}}"/>{new Date(plugin.lastUsed).toLocaleDateString('zh-CN', { month: 'short', day: 'numeric' })}</span>
          </div>
        </div>
        <Button variant="ghost" size="icon" className="h-7 w-7 flex-shrink-0" data-qoder-id="qel-h-7-4dc5fa62" data-qoder-source="{&quot;qoderId&quot;:&quot;qel-h-7-4dc5fa62&quot;,&quot;filePath&quot;:&quot;react-vite/src/components/workflow/PluginManager.jsx&quot;,&quot;componentName&quot;:&quot;PluginDetailCard&quot;,&quot;elementRole&quot;:&quot;h-7&quot;,&quot;loc&quot;:{&quot;line&quot;:190,&quot;column&quot;:9}}">
          {expanded ? <ChevronDown className="h-4 w-4"  data-qoder-id="qel-h-4-116f4631" data-qoder-source="{&quot;qoderId&quot;:&quot;qel-h-4-116f4631&quot;,&quot;filePath&quot;:&quot;react-vite/src/components/workflow/PluginManager.jsx&quot;,&quot;componentName&quot;:&quot;PluginDetailCard&quot;,&quot;elementRole&quot;:&quot;h-4&quot;,&quot;loc&quot;:{&quot;line&quot;:191,&quot;column&quot;:23}}"/> : <ChevronRight className="h-4 w-4"  data-qoder-id="qel-h-4-20729c62" data-qoder-source="{&quot;qoderId&quot;:&quot;qel-h-4-20729c62&quot;,&quot;filePath&quot;:&quot;react-vite/src/components/workflow/PluginManager.jsx&quot;,&quot;componentName&quot;:&quot;PluginDetailCard&quot;,&quot;elementRole&quot;:&quot;h-4&quot;,&quot;loc&quot;:{&quot;line&quot;:191,&quot;column&quot;:61}}"/>}
        </Button>
      </div>
      {expanded && (
        <div className="border-t px-4 py-4 space-y-4" style={{ borderColor: 'var(--cursor-border-10)' }} data-qoder-id="qel-border-t-d6ff9641" data-qoder-source="{&quot;qoderId&quot;:&quot;qel-border-t-d6ff9641&quot;,&quot;filePath&quot;:&quot;react-vite/src/components/workflow/PluginManager.jsx&quot;,&quot;componentName&quot;:&quot;PluginDetailCard&quot;,&quot;elementRole&quot;:&quot;border-t&quot;,&quot;loc&quot;:{&quot;line&quot;:195,&quot;column&quot;:9}}">
          <div className="grid grid-cols-2 gap-4" data-qoder-id="qel-grid-514fb6ec" data-qoder-source="{&quot;qoderId&quot;:&quot;qel-grid-514fb6ec&quot;,&quot;filePath&quot;:&quot;react-vite/src/components/workflow/PluginManager.jsx&quot;,&quot;componentName&quot;:&quot;PluginDetailCard&quot;,&quot;elementRole&quot;:&quot;grid&quot;,&quot;loc&quot;:{&quot;line&quot;:196,&quot;column&quot;:11}}">
            <FieldSchema title="输入字段" fields={plugin.inputFields} direction="in"  data-qoder-id="qel-fieldschema-1ed3f0de" data-qoder-source="{&quot;qoderId&quot;:&quot;qel-fieldschema-1ed3f0de&quot;,&quot;filePath&quot;:&quot;react-vite/src/components/workflow/PluginManager.jsx&quot;,&quot;componentName&quot;:&quot;PluginDetailCard&quot;,&quot;elementRole&quot;:&quot;fieldschema&quot;,&quot;loc&quot;:{&quot;line&quot;:197,&quot;column&quot;:13}}"/>
            <FieldSchema title="输出字段" fields={plugin.outputFields} direction="out"  data-qoder-id="qel-fieldschema-1dd3ef4b" data-qoder-source="{&quot;qoderId&quot;:&quot;qel-fieldschema-1dd3ef4b&quot;,&quot;filePath&quot;:&quot;react-vite/src/components/workflow/PluginManager.jsx&quot;,&quot;componentName&quot;:&quot;PluginDetailCard&quot;,&quot;elementRole&quot;:&quot;fieldschema&quot;,&quot;loc&quot;:{&quot;line&quot;:198,&quot;column&quot;:13}}"/>
          </div>
          <EndpointConfigPanel plugin={plugin}  data-qoder-id="qel-endpointconfigpanel-973add74" data-qoder-source="{&quot;qoderId&quot;:&quot;qel-endpointconfigpanel-973add74&quot;,&quot;filePath&quot;:&quot;react-vite/src/components/workflow/PluginManager.jsx&quot;,&quot;componentName&quot;:&quot;PluginDetailCard&quot;,&quot;elementRole&quot;:&quot;endpointconfigpanel&quot;,&quot;loc&quot;:{&quot;line&quot;:200,&quot;column&quot;:11}}"/>
          <PluginTestPanel plugin={plugin}  data-qoder-id="qel-plugintestpanel-9fda8235" data-qoder-source="{&quot;qoderId&quot;:&quot;qel-plugintestpanel-9fda8235&quot;,&quot;filePath&quot;:&quot;react-vite/src/components/workflow/PluginManager.jsx&quot;,&quot;componentName&quot;:&quot;PluginDetailCard&quot;,&quot;elementRole&quot;:&quot;plugintestpanel&quot;,&quot;loc&quot;:{&quot;line&quot;:201,&quot;column&quot;:11}}"/>
        </div>
      )}
    </div>
  )
}

/* ─── Plugin Manager (Main Export) — Cursor ─── */
export default function PluginManager(qoderProps) {
  const [plugins] = useState(PLUGINS)
  const [selectedPlugin, setSelectedPlugin] = useState(null)
  const [filterStatus, setFilterStatus] = useState('all')

  const filtered = filterStatus === 'all' ? plugins : plugins.filter((p) => p.status === filterStatus)
  const totalCalls = plugins.reduce((sum, p) => sum + p.callCount, 0)
  const activeCount = plugins.filter((p) => p.status === 'active').length

  return (
    <div className={["flex h-full flex-col", qoderProps?.className].filter(Boolean).join(" ")} data-component="plugin-manager" style={qoderProps?.style} data-qoder-id={qoderProps?.["data-qoder-id"]} data-qoder-source={qoderProps?.["data-qoder-source"]}>
      {/* Header — Cursor warm bar */}
      <div className="flex items-center justify-between border-b px-6 py-4" style={{ background: 'var(--cursor-surface-400)', borderColor: 'var(--cursor-border-10)' }} data-component="plugin-header" data-qoder-id="qel-plugin-header-cb4783af" data-qoder-source="{&quot;qoderId&quot;:&quot;qel-plugin-header-cb4783af&quot;,&quot;filePath&quot;:&quot;react-vite/src/components/workflow/PluginManager.jsx&quot;,&quot;componentName&quot;:&quot;PluginManager&quot;,&quot;elementRole&quot;:&quot;plugin-header&quot;,&quot;loc&quot;:{&quot;line&quot;:221,&quot;column&quot;:7}}">
        <div data-qoder-id="qel-div-9536be24" data-qoder-source="{&quot;qoderId&quot;:&quot;qel-div-9536be24&quot;,&quot;filePath&quot;:&quot;react-vite/src/components/workflow/PluginManager.jsx&quot;,&quot;componentName&quot;:&quot;PluginManager&quot;,&quot;elementRole&quot;:&quot;div&quot;,&quot;loc&quot;:{&quot;line&quot;:222,&quot;column&quot;:9}}">
          <h2 className="text-base font-semibold cursor-heading" style={{ color: 'var(--cursor-ink)' }} data-qoder-id="qel-text-base-edaabe84" data-qoder-source="{&quot;qoderId&quot;:&quot;qel-text-base-edaabe84&quot;,&quot;filePath&quot;:&quot;react-vite/src/components/workflow/PluginManager.jsx&quot;,&quot;componentName&quot;:&quot;PluginManager&quot;,&quot;elementRole&quot;:&quot;text-base&quot;,&quot;loc&quot;:{&quot;line&quot;:223,&quot;column&quot;:11}}">插件管理</h2>
          <p className="mt-0.5 text-xs cursor-serif" style={{ color: 'var(--cursor-border-55)' }} data-qoder-id="qel-mt-0-5-8d141bc6" data-qoder-source="{&quot;qoderId&quot;:&quot;qel-mt-0-5-8d141bc6&quot;,&quot;filePath&quot;:&quot;react-vite/src/components/workflow/PluginManager.jsx&quot;,&quot;componentName&quot;:&quot;PluginManager&quot;,&quot;elementRole&quot;:&quot;mt-0-5&quot;,&quot;loc&quot;:{&quot;line&quot;:224,&quot;column&quot;:11}}">管理 Coze 工作流插件，监控调用状态，测试接口</p>
        </div>
        <div className="flex items-center gap-3" data-qoder-id="qel-flex-7f7e68ac" data-qoder-source="{&quot;qoderId&quot;:&quot;qel-flex-7f7e68ac&quot;,&quot;filePath&quot;:&quot;react-vite/src/components/workflow/PluginManager.jsx&quot;,&quot;componentName&quot;:&quot;PluginManager&quot;,&quot;elementRole&quot;:&quot;flex&quot;,&quot;loc&quot;:{&quot;line&quot;:226,&quot;column&quot;:9}}">
          <div className="flex items-center gap-2 rounded-lg border px-3 py-1.5" style={{ background: 'var(--cursor-surface-100)', borderColor: 'var(--cursor-border-10)' }} data-qoder-id="qel-flex-807e6a3f" data-qoder-source="{&quot;qoderId&quot;:&quot;qel-flex-807e6a3f&quot;,&quot;filePath&quot;:&quot;react-vite/src/components/workflow/PluginManager.jsx&quot;,&quot;componentName&quot;:&quot;PluginManager&quot;,&quot;elementRole&quot;:&quot;flex&quot;,&quot;loc&quot;:{&quot;line&quot;:227,&quot;column&quot;:11}}">
            <Zap className="h-3.5 w-3.5" style={{ color: 'var(--cursor-orange)' }}  data-qoder-id="qel-h-3-5-225c4461" data-qoder-source="{&quot;qoderId&quot;:&quot;qel-h-3-5-225c4461&quot;,&quot;filePath&quot;:&quot;react-vite/src/components/workflow/PluginManager.jsx&quot;,&quot;componentName&quot;:&quot;PluginManager&quot;,&quot;elementRole&quot;:&quot;h-3-5&quot;,&quot;loc&quot;:{&quot;line&quot;:228,&quot;column&quot;:13}}"/>
            <span className="text-xs" style={{ color: 'var(--cursor-ink)' }} data-qoder-id="qel-text-xs-49e593be" data-qoder-source="{&quot;qoderId&quot;:&quot;qel-text-xs-49e593be&quot;,&quot;filePath&quot;:&quot;react-vite/src/components/workflow/PluginManager.jsx&quot;,&quot;componentName&quot;:&quot;PluginManager&quot;,&quot;elementRole&quot;:&quot;text-xs&quot;,&quot;loc&quot;:{&quot;line&quot;:229,&quot;column&quot;:13}}"><strong data-qoder-id="qel-strong-59af222e" data-qoder-source="{&quot;qoderId&quot;:&quot;qel-strong-59af222e&quot;,&quot;filePath&quot;:&quot;react-vite/src/components/workflow/PluginManager.jsx&quot;,&quot;componentName&quot;:&quot;PluginManager&quot;,&quot;elementRole&quot;:&quot;strong&quot;,&quot;loc&quot;:{&quot;line&quot;:229,&quot;column&quot;:78}}">{activeCount}</strong> 运行中</span>
            <span style={{ color: 'var(--cursor-border-10)' }} data-qoder-id="qel-span-daf8e4e3" data-qoder-source="{&quot;qoderId&quot;:&quot;qel-span-daf8e4e3&quot;,&quot;filePath&quot;:&quot;react-vite/src/components/workflow/PluginManager.jsx&quot;,&quot;componentName&quot;:&quot;PluginManager&quot;,&quot;elementRole&quot;:&quot;span&quot;,&quot;loc&quot;:{&quot;line&quot;:230,&quot;column&quot;:13}}">|</span>
            <span className="text-xs" style={{ color: 'var(--cursor-border-55)' }} data-qoder-id="qel-text-xs-4ee59b9d" data-qoder-source="{&quot;qoderId&quot;:&quot;qel-text-xs-4ee59b9d&quot;,&quot;filePath&quot;:&quot;react-vite/src/components/workflow/PluginManager.jsx&quot;,&quot;componentName&quot;:&quot;PluginManager&quot;,&quot;elementRole&quot;:&quot;text-xs&quot;,&quot;loc&quot;:{&quot;line&quot;:231,&quot;column&quot;:13}}">{totalCalls} 总调用</span>
          </div>
          <Button variant="ghost" size="sm" style={{ borderRadius: 'var(--seed-radius)' }} data-qoder-id="qel-button-d5cab605" data-qoder-source="{&quot;qoderId&quot;:&quot;qel-button-d5cab605&quot;,&quot;filePath&quot;:&quot;react-vite/src/components/workflow/PluginManager.jsx&quot;,&quot;componentName&quot;:&quot;PluginManager&quot;,&quot;elementRole&quot;:&quot;button&quot;,&quot;loc&quot;:{&quot;line&quot;:233,&quot;column&quot;:11}}"><ExternalLink className="h-3.5 w-3.5 mr-1"  data-qoder-id="qel-h-3-5-5aa77031" data-qoder-source="{&quot;qoderId&quot;:&quot;qel-h-3-5-5aa77031&quot;,&quot;filePath&quot;:&quot;react-vite/src/components/workflow/PluginManager.jsx&quot;,&quot;componentName&quot;:&quot;PluginManager&quot;,&quot;elementRole&quot;:&quot;h-3-5&quot;,&quot;loc&quot;:{&quot;line&quot;:233,&quot;column&quot;:92}}"/>Coze 控制台</Button>
          <Button variant="accent" size="sm" data-qoder-id="qel-button-d7cab92b" data-qoder-source="{&quot;qoderId&quot;:&quot;qel-button-d7cab92b&quot;,&quot;filePath&quot;:&quot;react-vite/src/components/workflow/PluginManager.jsx&quot;,&quot;componentName&quot;:&quot;PluginManager&quot;,&quot;elementRole&quot;:&quot;button&quot;,&quot;loc&quot;:{&quot;line&quot;:234,&quot;column&quot;:11}}"><Settings className="h-3.5 w-3.5 mr-1"  data-qoder-id="qel-h-3-5-c218961d" data-qoder-source="{&quot;qoderId&quot;:&quot;qel-h-3-5-c218961d&quot;,&quot;filePath&quot;:&quot;react-vite/src/components/workflow/PluginManager.jsx&quot;,&quot;componentName&quot;:&quot;PluginManager&quot;,&quot;elementRole&quot;:&quot;h-3-5&quot;,&quot;loc&quot;:{&quot;line&quot;:234,&quot;column&quot;:46}}"/>配置同步</Button>
        </div>
      </div>

      {/* Filter bar */}
      <div className="flex items-center gap-2 border-b px-6 py-2.5" style={{ borderColor: 'var(--cursor-border-10)' }} data-component="plugin-filters" data-qoder-id="qel-plugin-filters-62221235" data-qoder-source="{&quot;qoderId&quot;:&quot;qel-plugin-filters-62221235&quot;,&quot;filePath&quot;:&quot;react-vite/src/components/workflow/PluginManager.jsx&quot;,&quot;componentName&quot;:&quot;PluginManager&quot;,&quot;elementRole&quot;:&quot;plugin-filters&quot;,&quot;loc&quot;:{&quot;line&quot;:239,&quot;column&quot;:7}}">
        {[
          { key: 'all', label: '全部' },
          { key: 'active', label: '运行中' },
          { key: 'standby', label: '待命' },
        ].map((f) => (
          <Button key={f.key} variant="ghost" size="sm" onClick={() => setFilterStatus(f.key)}
            className={cn('h-7', filterStatus === f.key && 'bg-[var(--cursor-surface-500)] text-[var(--cursor-ink)] font-medium')}
            style={{ borderRadius: 'var(--seed-radius)' }} data-qoder-id="qel-button-b32e9cae" data-qoder-source="{&quot;qoderId&quot;:&quot;qel-button-b32e9cae&quot;,&quot;filePath&quot;:&quot;react-vite/src/components/workflow/PluginManager.jsx&quot;,&quot;componentName&quot;:&quot;PluginManager&quot;,&quot;elementRole&quot;:&quot;button&quot;,&quot;loc&quot;:{&quot;line&quot;:245,&quot;column&quot;:11}}">
            {f.label}
            <span className="ml-1 text-[10px] opacity-60" data-qoder-id="qel-ml-1-811b2eb2" data-qoder-source="{&quot;qoderId&quot;:&quot;qel-ml-1-811b2eb2&quot;,&quot;filePath&quot;:&quot;react-vite/src/components/workflow/PluginManager.jsx&quot;,&quot;componentName&quot;:&quot;PluginManager&quot;,&quot;elementRole&quot;:&quot;ml-1&quot;,&quot;loc&quot;:{&quot;line&quot;:249,&quot;column&quot;:13}}">{f.key === 'all' ? plugins.length : plugins.filter((p) => p.status === f.key).length}</span>
          </Button>
        ))}
      </div>

      {/* Plugin cards */}
      <div className="flex-1 overflow-y-auto scrollbar-thin p-6 space-y-3" data-component="plugin-list" data-qoder-id="qel-plugin-list-1c89641d" data-qoder-source="{&quot;qoderId&quot;:&quot;qel-plugin-list-1c89641d&quot;,&quot;filePath&quot;:&quot;react-vite/src/components/workflow/PluginManager.jsx&quot;,&quot;componentName&quot;:&quot;PluginManager&quot;,&quot;elementRole&quot;:&quot;plugin-list&quot;,&quot;loc&quot;:{&quot;line&quot;:255,&quot;column&quot;:7}}">
        {filtered.map((plugin) => (
          <PluginDetailCard key={plugin.id} plugin={plugin} isSelected={selectedPlugin?.id === plugin.id} onSelect={setSelectedPlugin}  data-qoder-id="qel-plugindetailcard-8e9bd1db" data-qoder-source="{&quot;qoderId&quot;:&quot;qel-plugindetailcard-8e9bd1db&quot;,&quot;filePath&quot;:&quot;react-vite/src/components/workflow/PluginManager.jsx&quot;,&quot;componentName&quot;:&quot;PluginManager&quot;,&quot;elementRole&quot;:&quot;plugindetailcard&quot;,&quot;loc&quot;:{&quot;line&quot;:257,&quot;column&quot;:11}}"/>
        ))}
        {filtered.length === 0 && (
          <div className="flex flex-col items-center justify-center py-16 text-center" data-qoder-id="qel-flex-d62a75d6" data-qoder-source="{&quot;qoderId&quot;:&quot;qel-flex-d62a75d6&quot;,&quot;filePath&quot;:&quot;react-vite/src/components/workflow/PluginManager.jsx&quot;,&quot;componentName&quot;:&quot;PluginManager&quot;,&quot;elementRole&quot;:&quot;flex&quot;,&quot;loc&quot;:{&quot;line&quot;:260,&quot;column&quot;:11}}">
            <Puzzle className="h-10 w-10 mb-3" style={{ color: 'var(--cursor-border-55)', opacity: 0.4 }}  data-qoder-id="qel-h-10-a875c677" data-qoder-source="{&quot;qoderId&quot;:&quot;qel-h-10-a875c677&quot;,&quot;filePath&quot;:&quot;react-vite/src/components/workflow/PluginManager.jsx&quot;,&quot;componentName&quot;:&quot;PluginManager&quot;,&quot;elementRole&quot;:&quot;h-10&quot;,&quot;loc&quot;:{&quot;line&quot;:261,&quot;column&quot;:13}}"/>
            <p className="text-sm cursor-serif" style={{ color: 'var(--cursor-border-55)' }} data-qoder-id="qel-text-sm-96188926" data-qoder-source="{&quot;qoderId&quot;:&quot;qel-text-sm-96188926&quot;,&quot;filePath&quot;:&quot;react-vite/src/components/workflow/PluginManager.jsx&quot;,&quot;componentName&quot;:&quot;PluginManager&quot;,&quot;elementRole&quot;:&quot;text-sm&quot;,&quot;loc&quot;:{&quot;line&quot;:262,&quot;column&quot;:13}}">暂无该状态的插件</p>
          </div>
        )}
      </div>

      {/* Footer status bar */}
      <div className="flex items-center justify-between border-t px-6 py-2" style={{ background: 'var(--cursor-surface-400)', borderColor: 'var(--cursor-border-10)' }} data-component="plugin-footer" data-qoder-id="qel-plugin-footer-7d967c05" data-qoder-source="{&quot;qoderId&quot;:&quot;qel-plugin-footer-7d967c05&quot;,&quot;filePath&quot;:&quot;react-vite/src/components/workflow/PluginManager.jsx&quot;,&quot;componentName&quot;:&quot;PluginManager&quot;,&quot;elementRole&quot;:&quot;plugin-footer&quot;,&quot;loc&quot;:{&quot;line&quot;:268,&quot;column&quot;:7}}">
        <div className="flex items-center gap-4 text-[10px]" style={{ color: 'var(--cursor-border-55)' }} data-qoder-id="qel-flex-de2cc105" data-qoder-source="{&quot;qoderId&quot;:&quot;qel-flex-de2cc105&quot;,&quot;filePath&quot;:&quot;react-vite/src/components/workflow/PluginManager.jsx&quot;,&quot;componentName&quot;:&quot;PluginManager&quot;,&quot;elementRole&quot;:&quot;flex&quot;,&quot;loc&quot;:{&quot;line&quot;:269,&quot;column&quot;:9}}">
          <span data-qoder-id="qel-span-a805eba2" data-qoder-source="{&quot;qoderId&quot;:&quot;qel-span-a805eba2&quot;,&quot;filePath&quot;:&quot;react-vite/src/components/workflow/PluginManager.jsx&quot;,&quot;componentName&quot;:&quot;PluginManager&quot;,&quot;elementRole&quot;:&quot;span&quot;,&quot;loc&quot;:{&quot;line&quot;:270,&quot;column&quot;:11}}">Coze API: <span className="font-medium" style={{ color: 'var(--cursor-success)' }} data-qoder-id="qel-font-medium-17274aee" data-qoder-source="{&quot;qoderId&quot;:&quot;qel-font-medium-17274aee&quot;,&quot;filePath&quot;:&quot;react-vite/src/components/workflow/PluginManager.jsx&quot;,&quot;componentName&quot;:&quot;PluginManager&quot;,&quot;elementRole&quot;:&quot;font-medium&quot;,&quot;loc&quot;:{&quot;line&quot;:270,&quot;column&quot;:27}}">已连接</span></span>
          <span data-qoder-id="qel-span-a605e87c" data-qoder-source="{&quot;qoderId&quot;:&quot;qel-span-a605e87c&quot;,&quot;filePath&quot;:&quot;react-vite/src/components/workflow/PluginManager.jsx&quot;,&quot;componentName&quot;:&quot;PluginManager&quot;,&quot;elementRole&quot;:&quot;span&quot;,&quot;loc&quot;:{&quot;line&quot;:271,&quot;column&quot;:11}}">Endpoint: api.coze.cn/v3</span>
          <span data-qoder-id="qel-span-a505e6e9" data-qoder-source="{&quot;qoderId&quot;:&quot;qel-span-a505e6e9&quot;,&quot;filePath&quot;:&quot;react-vite/src/components/workflow/PluginManager.jsx&quot;,&quot;componentName&quot;:&quot;PluginManager&quot;,&quot;elementRole&quot;:&quot;span&quot;,&quot;loc&quot;:{&quot;line&quot;:272,&quot;column&quot;:11}}">延迟: 42ms</span>
        </div>
        <span className="text-[10px]" style={{ color: 'var(--cursor-border-55)' }} data-qoder-id="qel-text-10px-58708813" data-qoder-source="{&quot;qoderId&quot;:&quot;qel-text-10px-58708813&quot;,&quot;filePath&quot;:&quot;react-vite/src/components/workflow/PluginManager.jsx&quot;,&quot;componentName&quot;:&quot;PluginManager&quot;,&quot;elementRole&quot;:&quot;text-10px&quot;,&quot;loc&quot;:{&quot;line&quot;:274,&quot;column&quot;:9}}">
          最后同步: {new Date().toLocaleTimeString('zh-CN', { hour: '2-digit', minute: '2-digit' })}
        </span>
      </div>
    </div>
  )
}
